# Generated by Django 2.1.4 on 2019-02-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('original', models.ImageField(upload_to='original')),
                ('mask', models.ImageField(blank=True, null=True, upload_to='mask')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('computed_materials', models.ManyToManyField(blank=True, related_name='computed', to='home.Material')),
                ('user_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='home.Material')),
            ],
        ),
    ]
